load("@llvm-project//llvm:lit_test.bzl", "lit_expand_template", "lit_test")
load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "utility",
    size = "small",
    srcs = ["utility.cpp"],
    linkstatic = True,
    deps = [
        "//src/toy",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@llvm-project//llvm:Support",
        "@std_module",
    ],
)

lit_expand_template(
    name = "lit_site_cfg_py",
    testonly = True,
    out = "lit.site.cfg.py",
    dirname_substitutions = {
        "@LLVM_TOOLS_DIR@": "@llvm-project//llvm:BUILD.bazel",
        "@TOY_TOOLS_DIR@": "//src/toy:BUILD.bazel",
    },
    template = "lit.site.cfg.py.in",
)

[
    lit_test(
        name = "{}.test".format(src),
        size = "small",
        srcs = [src],
        data = [
            "lit.cfg.py",
            "lit.site.cfg.py",
            "//src/toy:toyc",
            "@llvm-project//llvm:FileCheck",
            "@llvm-project//llvm:count",
            "@llvm-project//llvm:not",
        ],
    )
    for src in glob(["*.toy"])
]
