load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = [
    "//docs:__pkg__",
    "//src/library_usage:__subpackages__",
])

cc_library(
    name = "library_usage.mathematics",
    module_interfaces = ["mathematics/mod.cppm"],
    deps = [
        "@quill//:quill_module",
        "@std_module",
    ],
)

cc_binary(
    name = "library_usage",
    srcs = ["main.cpp"],
    deps = [
        ":library_usage.mathematics",
        "@boost.cobalt",
        "@quill//:quill_module",
        "@std_module",
    ],
)
