repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: &json5_files '^(\.devcontainer|\.vscode)/.*\.json$|\.json5$'
      - id: check-json5
        files: *json5_files
        types: [file]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v23.1.1
    hooks:
      - id: clang-format

  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 10.0.1
    hooks:
      - id: buildifier
