module(
    name = "monorepo",
    version = "latest",
)

# Dependencies

bazel_dep(name = "abseil-cpp", version = "20260817.0")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.9.2")
bazel_dep(name = "boost", version = "1.90.0.bcr.2")
bazel_dep(name = "boost.cobalt", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.unordered", version = "1.90.0.bcr.1")
bazel_dep(name = "cpptrace", version = "1.0.4.bcr.1")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "googletest", version = "1.18.0.bcr.1")
bazel_dep(name = "llvm", version = "0.8.21")  # See llvm-project/utils/bazel/MODULE.bazel
bazel_dep(name = "magic_enum", version = "0.9.8")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "quill", version = "13.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_python", version = "2.3.3")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "toolchains_llvm", version = "1.9.1")
bazel_dep(name = "zlib-ng", version = "2.3.3.bcr.2", repo_name = "llvm_zlib")  # See llvm-project/utils/bazel/MODULE.bazel
bazel_dep(name = "zstd", version = "1.5.7.bcr.2", repo_name = "llvm_zstd")  # See llvm-project/utils/bazel/MODULE.bazel

## cpptrace
git_override(
    module_name = "cpptrace",
    commit = "9edc08b0ffafc6231e5f7b1f4e81ac0c0ccf75f0",
    remote = "https://github.com/rdong8/cpptrace",
)

## rules_cc
git_override(
    module_name = "rules_cc",
    commit = "77b47b724ab05a076039f011a7295a4edce04d33",
    remote = "https://github.com/rdong8/rules_cc",
)

## quill
git_override(
    module_name = "quill",
    commit = "6fcd9c01d303acd613d64aca5fe0c084a87a50ac",
    remote = "https://github.com/odygrd/quill",
)

## toolchains_llvm

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    # TODO: https://github.com/bazelbuild/bazel-central-registry/pull/10539
    conly_flags = {
        "": [
            "-DZ_HAVE_UNISTD_H",
            "-D_DEFAULT_SOURCE",
        ],
        "linux-x86_64": [
            "-DZ_HAVE_UNISTD_H",
            "-D_DEFAULT_SOURCE",
        ],
    },
    cxx_standard = {"": "c++2d"},
    # TODO: make linker hermetic
    link_flags = {"": ["--ld-path=/home/linuxbrew/.linuxbrew/bin/wild"]},
    llvm_version = "23.1.1",
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

register_toolchains("@llvm_toolchain//:all")

# Dev dependencies

bazel_dep(name = "graphviz", version = "14.0.0.bcr.3", dev_dependency = True)
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
bazel_dep(name = "rules_doxygen", version = "2.6.4", dev_dependency = True)

## hedron_compile_commands
## TODO: use https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2977r1.html
git_override(
    module_name = "hedron_compile_commands",
    commit = "078ba7675c05bea2666c92d9a8abe200d8547655",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor",
)

## rules_doxygen

git_override(
    module_name = "rules_doxygen",
    commit = "482db671bfe9886d39831ef0e5e9e6b829f218f4",
    remote = "https://github.com/rdong8/rules_doxygen",
)

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")

doxygen_awesome = use_extension("//bazel:doxygen_awesome.bzl", "doxygen_awesome")
use_repo(doxygen_awesome, "doxygen_awesome")

# C++ std module

std_module = use_extension("//bazel:std_module.bzl", "std_module")
use_repo(std_module, "std_module")

# LLVM raw

llvm_raw = use_extension("//bazel:llvm.bzl", "llvm_raw")
use_repo(llvm_raw, "llvm-raw")

llvm_configure = use_repo_rule("@llvm-raw//utils/bazel:configure.bzl", "llvm_configure")

llvm_configure(
    name = "llvm-project",
    targets = ["X86"],
)
