module(
    name = "monorepo",
    version = "latest",
)

# C++ std module
std_module = use_extension("//bazel:std_module.bzl", "std_module")
use_repo(std_module, "std_module")

# LLVM raw

llvm_raw_deps = use_extension("//bazel:llvm.bzl", "llvm_raw_deps")
use_repo(llvm_raw_deps, "llvm-raw")

llvm_configure = use_repo_rule("@llvm-raw//utils/bazel:configure.bzl", "llvm_configure")

llvm_configure(
    name = "llvm-project",
    targets = ["X86"],
)

# Dependencies

bazel_dep(name = "abseil-cpp", version = "20260817.0")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "bazelrc-preset.bzl", version = "1.9.2")
bazel_dep(name = "boost", version = "1.90.0.bcr.2")
bazel_dep(name = "boost.cobalt", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.unordered", version = "1.90.0.bcr.1")
bazel_dep(name = "cpptrace", version = "1.0.4.bcr.1")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "googletest", version = "1.18.0.bcr.1")
bazel_dep(name = "llvm", version = "0.8.19")  # See llvm-project/utils/bazel/MODULE.bazel
bazel_dep(name = "magic_enum", version = "0.9.8")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "quill", version = "13.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_python", version = "2.3.3")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "toolchains_llvm", version = "1.9.0")
bazel_dep(name = "zlib-ng", version = "2.3.3.bcr.2", repo_name = "llvm_zlib")  # See llvm-project/utils/bazel/MODULE.bazel
bazel_dep(name = "zstd", version = "1.5.7.bcr.1", repo_name = "llvm_zstd")  # See llvm-project/utils/bazel/MODULE.bazel

## rules_cc
git_override(
    module_name = "rules_cc",
    commit = "6ce71cf3a76d931958141a430327ecbae688a903",
    remote = "https://github.com/rdong8/rules_cc",
)

## quill
git_override(
    module_name = "quill",
    commit = "6fcd9c01d303acd613d64aca5fe0c084a87a50ac",
    remote = "https://github.com/odygrd/quill",
)

## toolchains_llvm

git_override(
    module_name = "toolchains_llvm",
    commit = "2711d4189ff8c5670ecd1df46bbb1e758073fe78",
    remote = "https://github.com/bazel-contrib/toolchains_llvm",
)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    cxx_standard = {"": "c++2d"},
    # TODO: make linker hermetic
    link_flags = {"": ["--ld-path=/home/linuxbrew/.linuxbrew/bin/wild"]},
    llvm_version = "23.1.0",
)
use_repo(llvm, "llvm_toolchain", "llvm_toolchain_llvm")

register_toolchains("@llvm_toolchain//:all")

# Dev dependencies

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
bazel_dep(name = "rules_doxygen", version = "2.6.4", dev_dependency = True)

## hedron_compile_commands
## TODO: use https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2977r1.html
git_override(
    module_name = "hedron_compile_commands",
    commit = "a3ea4aa87b4539b3d6e356f49b3eb81f593e5656",
    remote = "https://github.com/rdong8/bazel-compile-commands-extractor",
)

## rules_doxygen

git_override(
    module_name = "rules_doxygen",
    commit = "7d6dc5494458bcba9159de927af6e6677621104d",
    remote = "https://github.com/TendTo/rules_doxygen",
)

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "doxygen_awesome_css",
    build_file_content = """
exports_files(["doxygen-awesome.css"])

filegroup(
    name = "css",
    srcs = ["doxygen-awesome.css"],
    visibility = ["//visibility:public"],
)
""",
    sha256 = "6f527e5733723bfd7243c28f24588dca4714cf977fea6147fdb4ae2050244409",
    strip_prefix = "doxygen-awesome-css-2.4.2",
    urls = ["https://github.com/jothepro/doxygen-awesome-css/archive/refs/tags/v2.4.2.tar.gz"],
)
