load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:private"])

cc_test(
    name = "utility",
    srcs = ["utility.cpp"],
    linkstatic = True,
    deps = [
        "//src/utility",
        "@cpptrace",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@llvm-project//llvm:Support",
        "@std_module",
    ],
)
