load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:private"])

cc_test(
    name = "utility",
    size = "small",
    srcs = ["utility.cpp"],
    # llvm-project and cpptrace both bring in their own libunwinds internally, for complicated reasons this causes a link-time symbol collision when dynamic linking
    linkstatic = True,
    deps = [
        "//src/utility",
        "@cpptrace",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "@std_module",
    ],
)
